#!/usr/bin/env bash
set -euo pipefail

INSTALL_DIR="$HOME/.vscode-tunnel"
BIN_DIR="$INSTALL_DIR/bin"
LOG_DIR="$INSTALL_DIR/logs"
SYSTEMD_DIR="$HOME/.config/systemd/user"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

log() { echo "[install] $1"; }

log "=== VS Code Tunnel Service Installer ==="

# ---- 1. Detect architecture and download VS Code CLI ----
if [ -x "$BIN_DIR/code" ]; then
    log "VS Code CLI already exists at $BIN_DIR/code, skipping download"
else
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64)  CLI_OS="cli-alpine-x64" ;;
        aarch64) CLI_OS="cli-alpine-arm64" ;;
        *)       log "ERROR: unsupported architecture: $ARCH"; exit 1 ;;
    esac
    log "Downloading VS Code CLI for $ARCH..."
    mkdir -p "$BIN_DIR"
    curl -fSL "https://code.visualstudio.com/sha/download?build=stable&os=$CLI_OS" -o /tmp/vscode-cli.tar.gz
    tar -xzf /tmp/vscode-cli.tar.gz -C "$BIN_DIR/"
    rm -f /tmp/vscode-cli.tar.gz
    if [ ! -x "$BIN_DIR/code" ]; then
        log "ERROR: download completed but $BIN_DIR/code is not executable"
        exit 1
    fi
    log "VS Code CLI installed to $BIN_DIR/code"
fi

# ---- 2. Copy scripts ----
log "Copying scripts to $INSTALL_DIR..."
cp "$SCRIPT_DIR/scripts/start-tunnel.sh" "$INSTALL_DIR/start-tunnel.sh"
cp "$SCRIPT_DIR/scripts/stop-tunnel.sh" "$INSTALL_DIR/stop-tunnel.sh"
cp "$SCRIPT_DIR/scripts/watchdog-tunnel.sh" "$INSTALL_DIR/watchdog-tunnel.sh"
chmod +x "$INSTALL_DIR/start-tunnel.sh"
chmod +x "$INSTALL_DIR/stop-tunnel.sh"
chmod +x "$INSTALL_DIR/watchdog-tunnel.sh"

# ---- 3. Generate env.sh ----
log "Generating env.sh..."

TMUX_PATH=$(command -v tmux) || { log "ERROR: tmux not found. Install tmux first."; exit 1; }
TMUX_DIR=$(dirname "$TMUX_PATH")
HOST_PATH=$(dirname "$(command -v host)") 2>/dev/null || HOST_PATH=""
SS_PATH=$(dirname "$(command -v ss)") 2>/dev/null || SS_PATH=""

PATH_PARTS="$BIN_DIR:$TMUX_DIR"
[ -n "$HOST_PATH" ] && PATH_PARTS="$PATH_PARTS:$HOST_PATH"
[ -n "$SS_PATH" ] && PATH_PARTS="$PATH_PARTS:$SS_PATH"
PATH_PARTS="$PATH_PARTS:/usr/local/bin:/usr/bin:/bin"

cat > "$INSTALL_DIR/env.sh" <<EOF
# Auto-generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Machine: $(hostname)
# Re-run install.sh to regenerate if PATH changes
export PATH="$PATH_PARTS"
EOF

log "env.sh generated with PATH=$PATH_PARTS"

# ---- 4. Copy systemd unit files ----
log "Installing systemd unit files to $SYSTEMD_DIR..."
mkdir -p "$SYSTEMD_DIR"
cp "$SCRIPT_DIR/systemd/vscode-tunnel.service" "$SYSTEMD_DIR/"
cp "$SCRIPT_DIR/systemd/vscode-tunnel-watchdog.service" "$SYSTEMD_DIR/"
cp "$SCRIPT_DIR/systemd/vscode-tunnel-watchdog.timer" "$SYSTEMD_DIR/"

# ---- 5. Create log directory ----
mkdir -p "$LOG_DIR"

# ---- 6. Check linger ----
LINGER_STATUS=$(loginctl show-user "$(whoami)" 2>/dev/null | grep "Linger=" || echo "Linger=unknown")
if [ "$LINGER_STATUS" != "Linger=yes" ]; then
    log ""
    log "WARNING: loginctl linger is not enabled for $(whoami)."
    log "The service will NOT start on boot without it."
    log "Run this command to enable it:"
    log ""
    log "    sudo loginctl enable-linger $(whoami)"
    log ""
    log "Then re-run this installer or manually start the services."
    log ""
fi

# ---- 7. Enable and start services ----
log "Reloading systemd and enabling services..."
systemctl --user daemon-reload
systemctl --user enable --now vscode-tunnel.service
systemctl --user enable --now vscode-tunnel-watchdog.timer

# ---- 8. Print status ----
log ""
log "=== Installation complete ==="
log ""
log "Service status:"
systemctl --user status vscode-tunnel.service --no-pager 2>&1 | head -5 || true
log ""
log "Timer status:"
systemctl --user status vscode-tunnel-watchdog.timer --no-pager 2>&1 | head -5 || true
log ""
log "Useful commands:"
log "  tmux attach -t vscode-tunnel          # Attach to tunnel session"
log "  cat ~/.vscode-tunnel/logs/tunnel.log   # View tunnel log"
log "  journalctl --user -u vscode-tunnel     # View systemd log"
log "  systemctl --user status vscode-tunnel  # Check service status"
log "  systemctl --user restart vscode-tunnel # Restart tunnel"
